package com.cpunisher.onmyojibot

import kotlinx.serialization.Serializable
import net.mamoe.mirai.console.data.AutoSavePluginData
import net.mamoe.mirai.console.data.value

object ShikigamiData: AutoSavePluginData("shikigami") {

    @Serializable
    data class Shikigami(
        val name: String,
        val id: Long,
    )

    val SSR: List<Shikigami> by value(listOf(
        Shikigami("大天狗", 217),
        Shikigami("酒吞童子", 219),
        Shikigami("荒川之主", 248),
        Shikigami("阎魔", 255),
        Shikigami("小鹿男", 259),
        Shikigami("茨木童子", 265),
        Shikigami("青行灯", 266),
        Shikigami("妖刀姬", 269),
        Shikigami("一目连", 272),
        Shikigami("花鸟卷", 279),
        Shikigami("辉夜姬", 280),
        Shikigami("荒", 283),
        Shikigami("彼岸花", 288),
        Shikigami("雪童子", 292),
        Shikigami("山风", 296),
        Shikigami("玉藻前", 300),
        Shikigami("御馔津", 304),
        Shikigami("面灵气", 311),
        Shikigami("鬼切", 312),
        Shikigami("白藏主", 316),
        Shikigami("八岐大蛇", 325),
        Shikigami("不知火", 330),
        Shikigami("大岳丸", 333),
        Shikigami("泷夜叉姬", 338),
        Shikigami("云外镜", 344),
        Shikigami("鬼童丸", 345),
        Shikigami("缘结神", 347),
        Shikigami("铃鹿御前", 351),
        Shikigami("紧那罗", 353),
        Shikigami("千姬", 356),
    ))

    val SP: List<Shikigami> by value(listOf(
        Shikigami("少羽大天狗", 315),
        Shikigami("炼狱茨木童子", 322),
        Shikigami("稻荷神御馔津", 326),
        Shikigami("苍风一目连", 327),
        Shikigami("赤影妖刀姬", 328),
        Shikigami("御怨般若", 331),
        Shikigami("骁浪荒川之主", 334),
        Shikigami("烬天玉藻前", 339),
        Shikigami("鬼王酒吞童子", 341),
        Shikigami("天剑韧心鬼切", 343),
        Shikigami("聆海金鱼姬", 346),
        Shikigami("浮世青行灯", 348),
        Shikigami("缚骨清姬", 352),
        Shikigami("待宵姑获鸟", 354),
        Shikigami("麓铭大岳丸", 355),
        Shikigami("初翎山风", 357),
        Shikigami("夜溟彼岸花", 358),
    ))

    val SR: List<Shikigami> by value(listOf(
        Shikigami("桃花妖", 200),
        Shikigami("雪女", 201),
        Shikigami("鬼使白", 210),
        Shikigami("鬼使黑", 211),
        Shikigami("孟婆", 215),
        Shikigami("犬神", 220),
        Shikigami("骨女", 223),
        Shikigami("鬼女红叶", 231),
        Shikigami("跳跳哥哥", 233),
        Shikigami("傀儡师", 242),
        Shikigami("海坊主", 247),
        Shikigami("判官", 251),
        Shikigami("凤凰火", 252),
        Shikigami("吸血姬", 253),
        Shikigami("妖狐", 254),
        Shikigami("妖琴师", 256),
        Shikigami("食梦貘", 257),
        Shikigami("清姬", 260),
        Shikigami("镰鼬", 261),
        Shikigami("姑获鸟", 262),
        Shikigami("二口女", 263),
        Shikigami("白狼", 264),
        Shikigami("樱花妖", 267),
        Shikigami("惠比寿", 268),
        Shikigami("络新妇", 270),
        Shikigami("般若", 271),
        Shikigami("青坊主", 273),
        Shikigami("夜叉", 276),
        Shikigami("黑童子", 277),
        Shikigami("白童子", 278),
        Shikigami("烟烟罗", 281),
        Shikigami("金鱼姬", 282),
        Shikigami("鸩", 285),
        Shikigami("以津真天", 286),
        Shikigami("匣中少女", 287),
        Shikigami("书翁", 291),
        Shikigami("百目鬼", 293),
        Shikigami("追月神", 295),
        Shikigami("熏", 298),
        Shikigami("弈", 303),
        Shikigami("猫掌柜", 307),
        Shikigami("淤菊虫", 318),
        Shikigami("一反木绵", 320),
        Shikigami("入殓师", 321),
        Shikigami("化鲸", 324),
        Shikigami("久次良", 332),
        Shikigami("蟹姬", 335),
        Shikigami("纸舞", 340),
        Shikigami("星熊童子", 342),
        Shikigami("风狸", 349),
        Shikigami("蝎女", 350),
    ))

    val R: List<Shikigami> by value(listOf(
        Shikigami("三尾狐", 202),
        Shikigami("座敷童子", 205),
        Shikigami("鲤鱼精", 206),
        Shikigami("九命猫", 207),
        Shikigami("狸猫", 208),
        Shikigami("河童", 209),
        Shikigami("童男", 212),
        Shikigami("童女", 213),
        Shikigami("饿鬼", 214),
        Shikigami("巫蛊师", 216),
        Shikigami("鸦天狗", 218),
        Shikigami("食发鬼", 221),
        Shikigami("武士之灵", 222),
        Shikigami("雨女", 224),
        Shikigami("跳跳弟弟", 225),
        Shikigami("跳跳妹妹", 226),
        Shikigami("兵俑", 227),
        Shikigami("丑时之女", 228),
        Shikigami("独眼小僧", 230),
        Shikigami("铁鼠", 232),
        Shikigami("椒图", 234),
        Shikigami("管狐", 236),
        Shikigami("山兔", 237),
        Shikigami("萤草", 238),
        Shikigami("蝴蝶精", 241),
        Shikigami("山童", 243),
        Shikigami("首无", 244),
        Shikigami("觉", 249),
        Shikigami("青蛙瓷器", 250),
        Shikigami("古笼火", 274),
        Shikigami("虫师", 306),
    ))
}