package com.cpunisher.onmyojibot

import kotlinx.serialization.Serializable
import net.mamoe.mirai.console.data.AutoSavePluginData
import net.mamoe.mirai.console.data.value

object ShikigamiData: AutoSavePluginData("shikigami") {

    @Serializable
    data class Shikigami(
        val name: String,
        val id: Long = 0,
    )

    val SSR: List<Shikigami> by value(listOf(
        Shikigami("大天狗"),
        Shikigami("酒吞童子"),
        Shikigami("荒川之主"),
        Shikigami("阎魔"),
        Shikigami("小鹿男"),
        Shikigami("茨木童子"),
        Shikigami("青行灯"),
        Shikigami("妖刀姬"),
        Shikigami("一目连"),
        Shikigami("花鸟卷"),
        Shikigami("辉夜姬"),
        Shikigami("荒"),
        Shikigami("彼岸花"),
        Shikigami("雪童子"),
        Shikigami("山风"),
        Shikigami("玉藻前"),
        Shikigami("御馔津"),
        Shikigami("面灵气"),
        Shikigami("鬼切"),
        Shikigami("白藏主"),
        Shikigami("八岐大蛇"),
        Shikigami("不知火"),
        Shikigami("大岳丸"),
        Shikigami("泷夜叉姬"),
        Shikigami("云外镜"),
        Shikigami("鬼童丸"),
        Shikigami("缘结神"),
        Shikigami("铃鹿御前"),
        Shikigami("紧那罗"),
        Shikigami("千姬"),
    ))

    val SP: List<Shikigami> by value(listOf(
        Shikigami("少羽大天狗"),
        Shikigami("炼狱茨木童子"),
        Shikigami("稻荷神御馔津"),
        Shikigami("苍风一目连"),
        Shikigami("赤影妖刀姬"),
        Shikigami("御怨般若"),
        Shikigami("骁浪荒川之主"),
        Shikigami("烬天玉藻前"),
        Shikigami("鬼王酒吞童子"),
        Shikigami("天剑韧心鬼切"),
        Shikigami("聆海金鱼姬"),
        Shikigami("浮世青行灯"),
        Shikigami("缚骨清姬"),
        Shikigami("待宵姑获鸟"),
        Shikigami("麓铭大岳丸"),
        Shikigami("初翎山风"),
        Shikigami("夜溟彼岸花"),
    ))

    val SR: List<Shikigami> by value(listOf(
        Shikigami("桃花妖"),
        Shikigami("雪女"),
        Shikigami("鬼使白"),
        Shikigami("鬼使黑"),
        Shikigami("孟婆"),
        Shikigami("犬神"),
        Shikigami("骨女"),
        Shikigami("鬼女红叶"),
        Shikigami("跳跳哥哥"),
        Shikigami("傀儡师"),
        Shikigami("海坊主"),
        Shikigami("判官"),
        Shikigami("凤凰火"),
        Shikigami("吸血姬"),
        Shikigami("妖狐"),
        Shikigami("妖琴师"),
        Shikigami("食梦貘"),
        Shikigami("清姬"),
        Shikigami("镰鼬"),
        Shikigami("姑获鸟"),
        Shikigami("二口女"),
        Shikigami("白狼"),
        Shikigami("樱花妖"),
        Shikigami("惠比寿"),
        Shikigami("络新妇"),
        Shikigami("般若"),
        Shikigami("青坊主"),
        Shikigami("夜叉"),
        Shikigami("黑童子"),
        Shikigami("白童子"),
        Shikigami("烟烟罗"),
        Shikigami("金鱼姬"),
        Shikigami("鸩"),
        Shikigami("以津真天"),
        Shikigami("匣中少女"),
        Shikigami("书翁"),
        Shikigami("百目鬼"),
        Shikigami("追月神"),
        Shikigami("熏"),
        Shikigami("弈"),
        Shikigami("猫掌柜"),
        Shikigami("淤菊虫"),
        Shikigami("一反木绵"),
        Shikigami("入殓师"),
        Shikigami("化鲸"),
        Shikigami("久次良"),
        Shikigami("蟹姬"),
        Shikigami("纸舞"),
        Shikigami("星熊童子"),
        Shikigami("风狸"),
        Shikigami("蝎女"),
    ))

    val R: List<Shikigami> by value(listOf(
        Shikigami("三尾狐"),
        Shikigami("座敷童子"),
        Shikigami("鲤鱼精"),
        Shikigami("九命猫"),
        Shikigami("狸猫"),
        Shikigami("河童"),
        Shikigami("童男"),
        Shikigami("童女"),
        Shikigami("饿鬼"),
        Shikigami("巫蛊师"),
        Shikigami("鸦天狗"),
        Shikigami("食发鬼"),
        Shikigami("武士之灵"),
        Shikigami("雨女"),
        Shikigami("跳跳弟弟"),
        Shikigami("跳跳妹妹"),
        Shikigami("兵俑"),
        Shikigami("丑时之女"),
        Shikigami("独眼小僧"),
        Shikigami("铁鼠"),
        Shikigami("椒图"),
        Shikigami("管狐"),
        Shikigami("山兔"),
        Shikigami("萤草"),
        Shikigami("蝴蝶精"),
        Shikigami("山童"),
        Shikigami("首无"),
        Shikigami("觉"),
        Shikigami("青蛙瓷器"),
        Shikigami("古笼火"),
        Shikigami("虫师"),
    ))
}